# Generated by Django 2.2.10 on 2020-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200430_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/covers'),
        ),
    ]
